/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteRouteImport } from './routes/$locale/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AndroidRouteImport } from './routes/android'
import { Route as AppertureRouteImport } from './routes/apperture'
import { Route as BufferiumRouteImport } from './routes/bufferium'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as FosRouteImport } from './routes/fos'
import { Route as FruitRouteImport } from './routes/fruit'
import { Route as LicensesRouteImport } from './routes/licenses'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleAboutRouteImport } from './routes/$locale/about'
import { Route as LocaleAndroidRouteImport } from './routes/$locale/android'
import { Route as LocaleAppertureRouteImport } from './routes/$locale/apperture'
import { Route as LocaleBufferiumRouteImport } from './routes/$locale/bufferium'
import { Route as LocaleContactRouteImport } from './routes/$locale/contact'
import { Route as LocaleDevelopersRouteImport } from './routes/$locale/developers'
import { Route as LocaleFosRouteImport } from './routes/$locale/fos'
import { Route as LocaleFruitRouteImport } from './routes/$locale/fruit'
import { Route as LocaleLicensesRouteImport } from './routes/$locale/licenses'
import { Route as LocalePrivacyRouteImport } from './routes/$locale/privacy'
import { Route as LocaleTermsRouteImport } from './routes/$locale/terms'
import { Route as LocaleAndroidIndexRouteImport } from './routes/$locale/android.index'
import { Route as LocaleAndroidAppRouteImport } from './routes/$locale/android.$app'
import { Route as LocaleAppertureIndexRouteImport } from './routes/$locale/apperture.index'
import { Route as LocaleAppertureAppRouteImport } from './routes/$locale/apperture.$app'
import { Route as LocaleBufferiumIndexRouteImport } from './routes/$locale/bufferium.index'
import { Route as LocaleBufferiumAppRouteImport } from './routes/$locale/bufferium.$app'
import { Route as LocaleFosIndexRouteImport } from './routes/$locale/fos.index'
import { Route as LocaleFosAppRouteImport } from './routes/$locale/fos.$app'
import { Route as LocaleFruitIndexRouteImport } from './routes/$locale/fruit.index'
import { Route as LocaleFruitAppRouteImport } from './routes/$locale/fruit.$app'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AndroidRoute = AndroidRouteImport.update({
  id: '/android',
  path: '/android',
  getParentRoute: () => rootRouteImport,
} as any)
const AppertureRoute = AppertureRouteImport.update({
  id: '/apperture',
  path: '/apperture',
  getParentRoute: () => rootRouteImport,
} as any)
const BufferiumRoute = BufferiumRouteImport.update({
  id: '/bufferium',
  path: '/bufferium',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const FosRoute = FosRouteImport.update({
  id: '/fos',
  path: '/fos',
  getParentRoute: () => rootRouteImport,
} as any)
const FruitRoute = FruitRouteImport.update({
  id: '/fruit',
  path: '/fruit',
  getParentRoute: () => rootRouteImport,
} as any)
const LicensesRoute = LicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleAndroidRoute = LocaleAndroidRouteImport.update({
  id: '/android',
  path: '/android',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleAppertureRoute = LocaleAppertureRouteImport.update({
  id: '/apperture',
  path: '/apperture',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleBufferiumRoute = LocaleBufferiumRouteImport.update({
  id: '/bufferium',
  path: '/bufferium',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleContactRoute = LocaleContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleDevelopersRoute = LocaleDevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleFosRoute = LocaleFosRouteImport.update({
  id: '/fos',
  path: '/fos',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleFruitRoute = LocaleFruitRouteImport.update({
  id: '/fruit',
  path: '/fruit',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleLicensesRoute = LocaleLicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocalePrivacyRoute = LocalePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleTermsRoute = LocaleTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleAndroidIndexRoute = LocaleAndroidIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleAndroidRoute,
} as any)
const LocaleAndroidAppRoute = LocaleAndroidAppRouteImport.update({
  id: '/$app',
  path: '/$app',
  getParentRoute: () => LocaleAndroidRoute,
} as any)
const LocaleAppertureIndexRoute = LocaleAppertureIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleAppertureRoute,
} as any)
const LocaleAppertureAppRoute = LocaleAppertureAppRouteImport.update({
  id: '/$app',
  path: '/$app',
  getParentRoute: () => LocaleAppertureRoute,
} as any)
const LocaleBufferiumIndexRoute = LocaleBufferiumIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleBufferiumRoute,
} as any)
const LocaleBufferiumAppRoute = LocaleBufferiumAppRouteImport.update({
  id: '/$app',
  path: '/$app',
  getParentRoute: () => LocaleBufferiumRoute,
} as any)
const LocaleFosIndexRoute = LocaleFosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleFosRoute,
} as any)
const LocaleFosAppRoute = LocaleFosAppRouteImport.update({
  id: '/$app',
  path: '/$app',
  getParentRoute: () => LocaleFosRoute,
} as any)
const LocaleFruitIndexRoute = LocaleFruitIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleFruitRoute,
} as any)
const LocaleFruitAppRoute = LocaleFruitAppRouteImport.update({
  id: '/$app',
  path: '/$app',
  getParentRoute: () => LocaleFruitRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/android': typeof AndroidRoute
  '/apperture': typeof AppertureRoute
  '/bufferium': typeof BufferiumRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/fos': typeof FosRoute
  '/fruit': typeof FruitRoute
  '/licenses': typeof LicensesRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/android': typeof LocaleAndroidRouteWithChildren
  '/$locale/apperture': typeof LocaleAppertureRouteWithChildren
  '/$locale/bufferium': typeof LocaleBufferiumRouteWithChildren
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/developers': typeof LocaleDevelopersRoute
  '/$locale/fos': typeof LocaleFosRouteWithChildren
  '/$locale/fruit': typeof LocaleFruitRouteWithChildren
  '/$locale/licenses': typeof LocaleLicensesRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/android/$app': typeof LocaleAndroidAppRoute
  '/$locale/apperture/$app': typeof LocaleAppertureAppRoute
  '/$locale/bufferium/$app': typeof LocaleBufferiumAppRoute
  '/$locale/fos/$app': typeof LocaleFosAppRoute
  '/$locale/fruit/$app': typeof LocaleFruitAppRoute
  '/$locale/android/': typeof LocaleAndroidIndexRoute
  '/$locale/apperture/': typeof LocaleAppertureIndexRoute
  '/$locale/bufferium/': typeof LocaleBufferiumIndexRoute
  '/$locale/fos/': typeof LocaleFosIndexRoute
  '/$locale/fruit/': typeof LocaleFruitIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/android': typeof AndroidRoute
  '/apperture': typeof AppertureRoute
  '/bufferium': typeof BufferiumRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/fos': typeof FosRoute
  '/fruit': typeof FruitRoute
  '/licenses': typeof LicensesRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/developers': typeof LocaleDevelopersRoute
  '/$locale/licenses': typeof LocaleLicensesRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/android/$app': typeof LocaleAndroidAppRoute
  '/$locale/apperture/$app': typeof LocaleAppertureAppRoute
  '/$locale/bufferium/$app': typeof LocaleBufferiumAppRoute
  '/$locale/fos/$app': typeof LocaleFosAppRoute
  '/$locale/fruit/$app': typeof LocaleFruitAppRoute
  '/$locale/android': typeof LocaleAndroidIndexRoute
  '/$locale/apperture': typeof LocaleAppertureIndexRoute
  '/$locale/bufferium': typeof LocaleBufferiumIndexRoute
  '/$locale/fos': typeof LocaleFosIndexRoute
  '/$locale/fruit': typeof LocaleFruitIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/android': typeof AndroidRoute
  '/apperture': typeof AppertureRoute
  '/bufferium': typeof BufferiumRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/fos': typeof FosRoute
  '/fruit': typeof FruitRoute
  '/licenses': typeof LicensesRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/android': typeof LocaleAndroidRouteWithChildren
  '/$locale/apperture': typeof LocaleAppertureRouteWithChildren
  '/$locale/bufferium': typeof LocaleBufferiumRouteWithChildren
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/developers': typeof LocaleDevelopersRoute
  '/$locale/fos': typeof LocaleFosRouteWithChildren
  '/$locale/fruit': typeof LocaleFruitRouteWithChildren
  '/$locale/licenses': typeof LocaleLicensesRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/android/$app': typeof LocaleAndroidAppRoute
  '/$locale/apperture/$app': typeof LocaleAppertureAppRoute
  '/$locale/bufferium/$app': typeof LocaleBufferiumAppRoute
  '/$locale/fos/$app': typeof LocaleFosAppRoute
  '/$locale/fruit/$app': typeof LocaleFruitAppRoute
  '/$locale/android/': typeof LocaleAndroidIndexRoute
  '/$locale/apperture/': typeof LocaleAppertureIndexRoute
  '/$locale/bufferium/': typeof LocaleBufferiumIndexRoute
  '/$locale/fos/': typeof LocaleFosIndexRoute
  '/$locale/fruit/': typeof LocaleFruitIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/about'
    | '/android'
    | '/apperture'
    | '/bufferium'
    | '/contact'
    | '/developers'
    | '/fos'
    | '/fruit'
    | '/licenses'
    | '/privacy'
    | '/terms'
    | '/$locale/about'
    | '/$locale/android'
    | '/$locale/apperture'
    | '/$locale/bufferium'
    | '/$locale/contact'
    | '/$locale/developers'
    | '/$locale/fos'
    | '/$locale/fruit'
    | '/$locale/licenses'
    | '/$locale/privacy'
    | '/$locale/terms'
    | '/$locale/'
    | '/$locale/android/$app'
    | '/$locale/apperture/$app'
    | '/$locale/bufferium/$app'
    | '/$locale/fos/$app'
    | '/$locale/fruit/$app'
    | '/$locale/android/'
    | '/$locale/apperture/'
    | '/$locale/bufferium/'
    | '/$locale/fos/'
    | '/$locale/fruit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/android'
    | '/apperture'
    | '/bufferium'
    | '/contact'
    | '/developers'
    | '/fos'
    | '/fruit'
    | '/licenses'
    | '/privacy'
    | '/terms'
    | '/$locale/about'
    | '/$locale/contact'
    | '/$locale/developers'
    | '/$locale/licenses'
    | '/$locale/privacy'
    | '/$locale/terms'
    | '/$locale'
    | '/$locale/android/$app'
    | '/$locale/apperture/$app'
    | '/$locale/bufferium/$app'
    | '/$locale/fos/$app'
    | '/$locale/fruit/$app'
    | '/$locale/android'
    | '/$locale/apperture'
    | '/$locale/bufferium'
    | '/$locale/fos'
    | '/$locale/fruit'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/about'
    | '/android'
    | '/apperture'
    | '/bufferium'
    | '/contact'
    | '/developers'
    | '/fos'
    | '/fruit'
    | '/licenses'
    | '/privacy'
    | '/terms'
    | '/$locale/about'
    | '/$locale/android'
    | '/$locale/apperture'
    | '/$locale/bufferium'
    | '/$locale/contact'
    | '/$locale/developers'
    | '/$locale/fos'
    | '/$locale/fruit'
    | '/$locale/licenses'
    | '/$locale/privacy'
    | '/$locale/terms'
    | '/$locale/'
    | '/$locale/android/$app'
    | '/$locale/apperture/$app'
    | '/$locale/bufferium/$app'
    | '/$locale/fos/$app'
    | '/$locale/fruit/$app'
    | '/$locale/android/'
    | '/$locale/apperture/'
    | '/$locale/bufferium/'
    | '/$locale/fos/'
    | '/$locale/fruit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AndroidRoute: typeof AndroidRoute
  AppertureRoute: typeof AppertureRoute
  BufferiumRoute: typeof BufferiumRoute
  ContactRoute: typeof ContactRoute
  DevelopersRoute: typeof DevelopersRoute
  FosRoute: typeof FosRoute
  FruitRoute: typeof FruitRoute
  LicensesRoute: typeof LicensesRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/android': {
      id: '/android'
      path: '/android'
      fullPath: '/android'
      preLoaderRoute: typeof AndroidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apperture': {
      id: '/apperture'
      path: '/apperture'
      fullPath: '/apperture'
      preLoaderRoute: typeof AppertureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bufferium': {
      id: '/bufferium'
      path: '/bufferium'
      fullPath: '/bufferium'
      preLoaderRoute: typeof BufferiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fos': {
      id: '/fos'
      path: '/fos'
      fullPath: '/fos'
      preLoaderRoute: typeof FosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fruit': {
      id: '/fruit'
      path: '/fruit'
      fullPath: '/fruit'
      preLoaderRoute: typeof FruitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licenses': {
      id: '/licenses'
      path: '/licenses'
      fullPath: '/licenses'
      preLoaderRoute: typeof LicensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/android': {
      id: '/$locale/android'
      path: '/android'
      fullPath: '/$locale/android'
      preLoaderRoute: typeof LocaleAndroidRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/apperture': {
      id: '/$locale/apperture'
      path: '/apperture'
      fullPath: '/$locale/apperture'
      preLoaderRoute: typeof LocaleAppertureRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/bufferium': {
      id: '/$locale/bufferium'
      path: '/bufferium'
      fullPath: '/$locale/bufferium'
      preLoaderRoute: typeof LocaleBufferiumRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/contact': {
      id: '/$locale/contact'
      path: '/contact'
      fullPath: '/$locale/contact'
      preLoaderRoute: typeof LocaleContactRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/developers': {
      id: '/$locale/developers'
      path: '/developers'
      fullPath: '/$locale/developers'
      preLoaderRoute: typeof LocaleDevelopersRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/fos': {
      id: '/$locale/fos'
      path: '/fos'
      fullPath: '/$locale/fos'
      preLoaderRoute: typeof LocaleFosRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/fruit': {
      id: '/$locale/fruit'
      path: '/fruit'
      fullPath: '/$locale/fruit'
      preLoaderRoute: typeof LocaleFruitRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/licenses': {
      id: '/$locale/licenses'
      path: '/licenses'
      fullPath: '/$locale/licenses'
      preLoaderRoute: typeof LocaleLicensesRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/privacy': {
      id: '/$locale/privacy'
      path: '/privacy'
      fullPath: '/$locale/privacy'
      preLoaderRoute: typeof LocalePrivacyRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/terms': {
      id: '/$locale/terms'
      path: '/terms'
      fullPath: '/$locale/terms'
      preLoaderRoute: typeof LocaleTermsRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/android/': {
      id: '/$locale/android/'
      path: '/'
      fullPath: '/$locale/android/'
      preLoaderRoute: typeof LocaleAndroidIndexRouteImport
      parentRoute: typeof LocaleAndroidRoute
    }
    '/$locale/android/$app': {
      id: '/$locale/android/$app'
      path: '/$app'
      fullPath: '/$locale/android/$app'
      preLoaderRoute: typeof LocaleAndroidAppRouteImport
      parentRoute: typeof LocaleAndroidRoute
    }
    '/$locale/apperture/': {
      id: '/$locale/apperture/'
      path: '/'
      fullPath: '/$locale/apperture/'
      preLoaderRoute: typeof LocaleAppertureIndexRouteImport
      parentRoute: typeof LocaleAppertureRoute
    }
    '/$locale/apperture/$app': {
      id: '/$locale/apperture/$app'
      path: '/$app'
      fullPath: '/$locale/apperture/$app'
      preLoaderRoute: typeof LocaleAppertureAppRouteImport
      parentRoute: typeof LocaleAppertureRoute
    }
    '/$locale/bufferium/': {
      id: '/$locale/bufferium/'
      path: '/'
      fullPath: '/$locale/bufferium/'
      preLoaderRoute: typeof LocaleBufferiumIndexRouteImport
      parentRoute: typeof LocaleBufferiumRoute
    }
    '/$locale/bufferium/$app': {
      id: '/$locale/bufferium/$app'
      path: '/$app'
      fullPath: '/$locale/bufferium/$app'
      preLoaderRoute: typeof LocaleBufferiumAppRouteImport
      parentRoute: typeof LocaleBufferiumRoute
    }
    '/$locale/fos/': {
      id: '/$locale/fos/'
      path: '/'
      fullPath: '/$locale/fos/'
      preLoaderRoute: typeof LocaleFosIndexRouteImport
      parentRoute: typeof LocaleFosRoute
    }
    '/$locale/fos/$app': {
      id: '/$locale/fos/$app'
      path: '/$app'
      fullPath: '/$locale/fos/$app'
      preLoaderRoute: typeof LocaleFosAppRouteImport
      parentRoute: typeof LocaleFosRoute
    }
    '/$locale/fruit/': {
      id: '/$locale/fruit/'
      path: '/'
      fullPath: '/$locale/fruit/'
      preLoaderRoute: typeof LocaleFruitIndexRouteImport
      parentRoute: typeof LocaleFruitRoute
    }
    '/$locale/fruit/$app': {
      id: '/$locale/fruit/$app'
      path: '/$app'
      fullPath: '/$locale/fruit/$app'
      preLoaderRoute: typeof LocaleFruitAppRouteImport
      parentRoute: typeof LocaleFruitRoute
    }
  }
}

interface LocaleAndroidRouteChildren {
  LocaleAndroidAppRoute: typeof LocaleAndroidAppRoute
  LocaleAndroidIndexRoute: typeof LocaleAndroidIndexRoute
}

const LocaleAndroidRouteChildren: LocaleAndroidRouteChildren = {
  LocaleAndroidAppRoute: LocaleAndroidAppRoute,
  LocaleAndroidIndexRoute: LocaleAndroidIndexRoute,
}

const LocaleAndroidRouteWithChildren = LocaleAndroidRoute._addFileChildren(
  LocaleAndroidRouteChildren,
)

interface LocaleAppertureRouteChildren {
  LocaleAppertureAppRoute: typeof LocaleAppertureAppRoute
  LocaleAppertureIndexRoute: typeof LocaleAppertureIndexRoute
}

const LocaleAppertureRouteChildren: LocaleAppertureRouteChildren = {
  LocaleAppertureAppRoute: LocaleAppertureAppRoute,
  LocaleAppertureIndexRoute: LocaleAppertureIndexRoute,
}

const LocaleAppertureRouteWithChildren = LocaleAppertureRoute._addFileChildren(
  LocaleAppertureRouteChildren,
)

interface LocaleBufferiumRouteChildren {
  LocaleBufferiumAppRoute: typeof LocaleBufferiumAppRoute
  LocaleBufferiumIndexRoute: typeof LocaleBufferiumIndexRoute
}

const LocaleBufferiumRouteChildren: LocaleBufferiumRouteChildren = {
  LocaleBufferiumAppRoute: LocaleBufferiumAppRoute,
  LocaleBufferiumIndexRoute: LocaleBufferiumIndexRoute,
}

const LocaleBufferiumRouteWithChildren = LocaleBufferiumRoute._addFileChildren(
  LocaleBufferiumRouteChildren,
)

interface LocaleFosRouteChildren {
  LocaleFosAppRoute: typeof LocaleFosAppRoute
  LocaleFosIndexRoute: typeof LocaleFosIndexRoute
}

const LocaleFosRouteChildren: LocaleFosRouteChildren = {
  LocaleFosAppRoute: LocaleFosAppRoute,
  LocaleFosIndexRoute: LocaleFosIndexRoute,
}

const LocaleFosRouteWithChildren = LocaleFosRoute._addFileChildren(
  LocaleFosRouteChildren,
)

interface LocaleFruitRouteChildren {
  LocaleFruitAppRoute: typeof LocaleFruitAppRoute
  LocaleFruitIndexRoute: typeof LocaleFruitIndexRoute
}

const LocaleFruitRouteChildren: LocaleFruitRouteChildren = {
  LocaleFruitAppRoute: LocaleFruitAppRoute,
  LocaleFruitIndexRoute: LocaleFruitIndexRoute,
}

const LocaleFruitRouteWithChildren = LocaleFruitRoute._addFileChildren(
  LocaleFruitRouteChildren,
)

interface LocaleRouteRouteChildren {
  LocaleAboutRoute: typeof LocaleAboutRoute
  LocaleAndroidRoute: typeof LocaleAndroidRouteWithChildren
  LocaleAppertureRoute: typeof LocaleAppertureRouteWithChildren
  LocaleBufferiumRoute: typeof LocaleBufferiumRouteWithChildren
  LocaleContactRoute: typeof LocaleContactRoute
  LocaleDevelopersRoute: typeof LocaleDevelopersRoute
  LocaleFosRoute: typeof LocaleFosRouteWithChildren
  LocaleFruitRoute: typeof LocaleFruitRouteWithChildren
  LocaleLicensesRoute: typeof LocaleLicensesRoute
  LocalePrivacyRoute: typeof LocalePrivacyRoute
  LocaleTermsRoute: typeof LocaleTermsRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaleAboutRoute: LocaleAboutRoute,
  LocaleAndroidRoute: LocaleAndroidRouteWithChildren,
  LocaleAppertureRoute: LocaleAppertureRouteWithChildren,
  LocaleBufferiumRoute: LocaleBufferiumRouteWithChildren,
  LocaleContactRoute: LocaleContactRoute,
  LocaleDevelopersRoute: LocaleDevelopersRoute,
  LocaleFosRoute: LocaleFosRouteWithChildren,
  LocaleFruitRoute: LocaleFruitRouteWithChildren,
  LocaleLicensesRoute: LocaleLicensesRoute,
  LocalePrivacyRoute: LocalePrivacyRoute,
  LocaleTermsRoute: LocaleTermsRoute,
  LocaleIndexRoute: LocaleIndexRoute,
}

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AndroidRoute: AndroidRoute,
  AppertureRoute: AppertureRoute,
  BufferiumRoute: BufferiumRoute,
  ContactRoute: ContactRoute,
  DevelopersRoute: DevelopersRoute,
  FosRoute: FosRoute,
  FruitRoute: FruitRoute,
  LicensesRoute: LicensesRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
