/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppertureRouteImport } from './routes/apperture'
import { Route as FruitRouteImport } from './routes/fruit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppertureRoute = AppertureRouteImport.update({
  id: '/apperture',
  path: '/apperture',
  getParentRoute: () => rootRouteImport,
} as any)
const FruitRoute = FruitRouteImport.update({
  id: '/fruit',
  path: '/fruit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apperture': typeof AppertureRoute
  '/fruit': typeof FruitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apperture': typeof AppertureRoute
  '/fruit': typeof FruitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apperture': typeof AppertureRoute
  '/fruit': typeof FruitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/apperture' | '/fruit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/apperture' | '/fruit'
  id: '__root__' | '/' | '/apperture' | '/fruit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppertureRoute: typeof AppertureRoute
  FruitRoute: typeof FruitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apperture': {
      id: '/apperture'
      path: '/apperture'
      fullPath: '/apperture'
      preLoaderRoute: typeof AppertureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fruit': {
      id: '/fruit'
      path: '/fruit'
      fullPath: '/fruit'
      preLoaderRoute: typeof FruitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppertureRoute: AppertureRoute,
  FruitRoute: FruitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
